### PR TITLE
chore: improves tests negative

### PR DESCRIPTION
**Pull request by vuvoth**
# Changes 

- Make test more simple
- Use should panic macro

### CODE REVIEW

**Comment by katat** [comment]
This simplifies the code a lot. But can we just use function instead of macro to achieve the same?

**Comment by vuvoth** [comment]
> This simplifies the code a lot, thanks! But can we just use function instead of macro to achieve the same?

We can. However, we need create the function warps this function with #[test] macros for every test.

**Comment by katat** [comment]
Hmm, yeah. But I think it is fine to use #[test] as it is a common practice for testing, and it is more explicit for code reading.

We are trying to avoid creating custom macros as much as possible, since they are generally harder to comprehend.

**Comment by vuvoth** [comment]
Got it! So I will update PR. 
Btw I'm planing to add more tests for packages.

**Comment by vuvoth** [comment]
Hi @katat! 
We can't pass something like ErrorKind::ReturnTypeMismatch(..) to function params. I also think the macro is not so hard to read in this case.

**Comment by mimoo** [comment]
I agree with @katat here that macros should be sort of used as last case resort as they're easy to maintain/update, I don't think the changes are impactful enough here to warrant the introduction of a macro

**Comment by vuvoth** [comment]
Hey @mimoo, @katat! 
Please review my PR again!

**Comment by mimoo** [comment]
closing for now, feel free to reopen

**Pull request closed without merging**
