### PR TITLE
Improve error when a keyword is used as identifier

### PR DESCRIPTION
**Pull request by zedar**
This PR addresses this issue: https://github.com/zksecurity/noname/issues/236

### CODE REVIEW

**Review by katat — APPROVED** [review]
Thanks! Looks good to me.

**Comment by zedar** [comment]
Thanks @katat , will you merge it?

**Comment by mimoo** [comment]
can you post a screenshot of the error?

**Comment by zedar** [comment]
There it is:
image

**Comment by mimoo** [comment]
looks great thanks so much :) and nice terminal

**Pull request merged**
