### PR TITLE
Feat: noname cli: read input/output JSON from file

### LINKED ISSUE #92: noname cli: read input/output JSON from file
# Motivation 
We only read public input/output by passed in the cli as a string. This is good if we can read input from file. 

```bash
 cargo run test --backend r1cs-bn254 --path examples/arithmetic.no --private-inputs '{"private_input": "1"}' --public-inputs '{"public_input": "1"}' --debug
```
We can make cli above more simple: 

```bash
 cargo run test --backend r1cs-bn254 --path examples/arithmetic.no --private-inputs private_input.json --public-inputs ./public_inputs.json--debug 
```

# How to solve it?  
- Add option to read json file from cli.
- Rename --private-inputs, --public-inputs to --private-inputs-str... 

Another solution is try parse json, if can not we will try parse as file path.

### PR DESCRIPTION
**Pull request by ibkisthere**
Closes #92 
There's a lot of changes - i'll briefly summarize what i did  

- I added a way to parse JSON files to the noname-cli , following the second option on #92 , it first tries to parse json, if it can not we will try parse as file path. 
- if the path/ file is invalid (it does not exists, or it is a directory) it panics immediately and shows an error message on the console 
- added 2 more Error types to the ParsingError Enum for the invalid path/ file does not exist error and path is directory
-  added an inputs folder and two folders under it for testing valid and invalid json public_inputs and private_inputs 

Here are some example commands to test the new changes to the cli

```cargo run test --backend r1cs-bn254 --path examples/arithmetic.no --private-inputs '{"private_input": "2"}' --public-inputs '{"public_input": "2"}' --debug```

``` cargo run test --backend r1cs-bn254 --path examples/arithmetic.no --private-inputs examples/json/inputs1/private_input.json --public-inputs examples/json/inputs1/public_input.json --debug```

### CODE REVIEW

**Review by mimoo — APPROVED** [review]
this is great, thanks! The only problem that I see is that we're not making use of the examples/json/* files right?

**Comment by ibkisthere** [comment]
Oh i understand you , i only tested the inputs manually by writing commands to the paths to the files, i didn't write actual tests , i'm just seeing a test folder in the repo just now, i can do that.

**Comment by mimoo** [comment]
we ended up merging this one: https://github.com/zksecurity/noname/pull/111 but if you want to add your comments to the CLI usage that would still be great!

**Comment by ibkisthere** [comment]
Will do !

**Comment by mimoo** [comment]
I'll close this one for now!

**Pull request closed without merging**
