### PR TITLE
refactor: bump to current Kimchi proof system revision

### PR DESCRIPTION
**Pull request by binadamu-isiyoonekana**
## Description

This Pull Request (PR) aims at refactoring the current version of `Noname` so that it supports a more recent version of the [Kimchi](https://github.com/o1-labs/proof-systems/tree/master/kimchi) proof system.

The present code compiles and executes successfully with revision [a5d8883ddf649c22f38aaac122d368ecb9fa2230](https://github.com/o1-labs/proof-systems/tree/a5d8883ddf649c22f38aaac122d368ecb9fa2230) of Kimchi.

All current tests passed and none (i.e. unit, integration or property-based tests) were added.

## Type of change

Minor refactoring changes impacting mostly the [`prover`](src/prover.rs), [witness](src/witness.rs) and some cryptographic primitives.

## Test Configuration

* Rust version: 1.76.0-nightly
* Hardware: MacBook Pro (x86)
* OS: MacOS 14.1.2 (Sonoma)

### CODE REVIEW

**Comment by mimoo** [comment]
Thanks for the PR! what prompted you to do this btw if I may ask :) ? working on anything interesting?

**Comment by mimoo** [comment]
can you run `cargo fmt`? Then I can merge it! Thanks again :)

**Comment by binadamu-isiyoonekana** [comment]
> Thanks for the PR! what prompted you to do this btw if I may ask :) ? working on anything interesting?

Hi David. I'm currently exploring folding schemes on Plonk with Sangria, and ultimately, the Kimchi proof system. I thank you very much for your language, as it is the perfect starting point for generating Plonk circuits. Merci :)

**Comment by binadamu-isiyoonekana** [comment]
Hello David,
  I know this is not the right place to ask (and issue will be more appropriate), but I would just like to know if you're aware of this error when running the simple [`arithmetic.no`](https://github.com/zksecurity/noname/blob/main/examples/arithmetic.no) circuit?

```sh  
$ cargo run -- test --path examples/arithmetic.no --debug --private-inputs '{"private_input": ["1"]}' --public-inputs '{"public_input":["1"]}'

thread 'main' panicked at src/circuit_writer/mod.rs:307:13:
the circuit is either too small or does not constrain anything (TODO: better error)
```
Why this constraint of [2 gates](https://github.com/zksecurity/noname/blob/de947be6b9232888c14afc77d20e727d4b634765/src/circuit_writer/mod.rs#L305) for Kimchi, by the way?

Thanks David.

**Comment by mimoo** [comment]
Ah, there was some assumptions in kimchi that don't work with circuits that are too small, it's probably fixable but since people don't generally write small circuits like that we didn't. Now I'm wondering why `arithmetic.no` produces such a small circuit though... I'll have to investigate.

Anyway thanks for the PR again! If you're interested there's more opportunities to contribute to this repo :D we also have a group chat for questions/discussions https://t.me/+VSChAOmJQgQzODcx

**Comment by mimoo** [comment]
ah clippy is not happy, well we should take care of that in another PR anyway.

**Pull request merged**
