### PR TITLE
chore(ci): fix installation step

### PR DESCRIPTION
**Pull request by eightfilms**
fixes https://github.com/zksecurity/noname/actions/runs/9376759481

### CODE REVIEW

**Comment by katat** [comment]
Yeah, I was trying to fix this :)

**Comment by eightfilms** [comment]
seems to be building on my fork: https://github.com/eightfilms/noname/actions/runs/9376847691

**Comment by eightfilms** [comment]
seems like there's now some sort of permission error? @katat

**Comment by katat** [comment]
it should work now: https://github.com/zksecurity/noname/pull/98

cheers!

**Pull request merged**
