### PR TITLE
Added test coverage checks on the constraint

### PR DESCRIPTION
**Pull request by ronantakizawa**
Added test coverage checks on the constraint. Resolves issue #49.

### CODE REVIEW

**Comment by katat** [comment]
Thanks for working on this.

I think the issue is about increasing the test coverage, where the 
Currently we have two major group of tests:
- **Example tests**, which cover the positives. Each example demonstrates language feature. At the end of the testing, it compare the asm with the baseline to see if discrepancy exists. If exists discrepancy, it meant something critical happened unexpectedly in the process of circuit generation.
- **Negative tests**, which makes sure certain checks are done in the compilation pipeline. There are a couple different phases: AST -> NAST -> TAST -> MAST -> Synthesizer. Currently there is a degree of testing coverage for TAST, MAST and Synthesizer, which are done in the `negative_tests.rs`

Maybe the priority at the moment is to review the current tests in the `negative_tests.rs` and

**Comment by katat** [comment]
Thanks for working on this.

Currently we have two major group of tests:
- **Example tests**, which cover the positives. Each example demonstrates language feature. At the end of the testing, it compare the asm with the baseline to see if discrepancy exists. If exists discrepancy, it meant something critical happened unexpectedly in the process of circuit generation.
- **Negative tests**, which makes sure certain checks are done in the compilation pipeline. There are a couple different phases: AST -> NAST -> TAST -> MAST -> Synthesizer. Currently there is a degree of testing coverage for TAST, MAST and Synthesizer, which are done in the `negative_tests.rs`


I think the issue is about increasing the test coverage, where it is relatively critical in the compilation pipeline atm.
Maybe the priority is to review the current tests in the `negative_tests.rs` and increase the coverage for the different compilation phases there.

**Comment by ronantakizawa** [comment]
I added phase tests in `negative_tests.rs` as well as tests that verify failures for incorrect arithmetic operations. Let me know if I should add / remove tests 👍

**Comment by katat** [comment]
Oh, sorry forgot to mention that: It'd better to check out the `negative_tests.rs` in the ongoing PR https://github.com/zksecurity/noname/pull/147, which got better examples on how to add negative tests.

**Comment by ronantakizawa** [comment]
@katat PR is continued to PR #179 (It was easier to make a new PR merging into rfc-0-impl instead of using this current PR).

**Pull request closed without merging**
